/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrOwnerRepoNumberRouteImport } from './routes/pr.$owner.$repo.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrOwnerRepoNumberRoute = PrOwnerRepoNumberRouteImport.update({
  id: '/pr/$owner/$repo/$number',
  path: '/pr/$owner/$repo/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pr/$owner/$repo/$number': typeof PrOwnerRepoNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pr/$owner/$repo/$number': typeof PrOwnerRepoNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pr/$owner/$repo/$number': typeof PrOwnerRepoNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pr/$owner/$repo/$number'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pr/$owner/$repo/$number'
  id: '__root__' | '/' | '/pr/$owner/$repo/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrOwnerRepoNumberRoute: typeof PrOwnerRepoNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr/$owner/$repo/$number': {
      id: '/pr/$owner/$repo/$number'
      path: '/pr/$owner/$repo/$number'
      fullPath: '/pr/$owner/$repo/$number'
      preLoaderRoute: typeof PrOwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrOwnerRepoNumberRoute: PrOwnerRepoNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
